function holehelper;
%BWS March 2016 - initial template
%Junle Cai - notes.. 
%BWS November 2016 working over Junle Cai modifications.. Commenting is not
%so great in this code since very little provided. Trying to clean up as I
%go, but a lot of work to get this into final shape.
%
%general
global fig screen prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all neigs version screen
%output from pre2
global subfig ed_prop ed_node ed_elem ed_lengths axestop screen flags modeflag ed_springs ed_constraints
%output from load file
global filename
%output from holehelper
global popanel flags axessect input1edit input2edit input3edit label_cs axeslong b bl1 bl2 bl3  axescurve_hole axes2dshape_hole
global halfwave hint waveedit label_title len_cur_local uplengthl downlengthl

global undefl nodel eleml model axes2dshapel scalel springsl m_al BCl SurfPosl shapesl len_cur_distorl idx_hole_l lengths_local  curve_local 
global curvecelll filenamecelll clascelll filedisplayl minoptl logoptl clasoptl axescurvel xminl xmaxl yminl ymaxl modedisplayl  fileindexl modeindexl picpointl
global screen Ix_avg Iy_avg I1_avg I2_avg len_cur_local modeindex lengthindex
global xmin xmax ymin ymax modeindex_local picpoint curvel shapescelll J_avg Cw_avg record_hole table_hole
global popanel_hole flags_hole flag_s xcg zcg thetap A I11 I22 w Cw  Pedit_hole Bedit_hole M11edit_hole M22edit_hole S2edit input_Lcrd_edit upperbox
global   out2A out2J out2xcg out2zcg out2Ixx out2Izz out2Ixz out2thetap out2I11 out2I22 out2C_w lowerbox
global KL1edit KL2edit KL3edit range_slider
global Pedit_hole M11edit_hole M22edit_hole
%This is code to run this tool as a subfigure
%comment out and uncomment section below depending on how interface desired
% subfig=figure;
% name=['CUFSM v',version,' -- Hole Effect Analysis Tool'];
% set(subfig,'Name',name,'NumberTitle','off');
% set(subfig,'MenuBar','none');
% set(subfig,'position',[50 70 1024 633])%

%This is code to run this tool in the main screen
clf
pause(0.01)
name=['CUFSM v',version,' -- Hole Effect Analysis Tool'];
set(fig,'Name',name);
subfig=fig;
screen=9;
commandbar;
%
%------------------------------------------------------------------------------------
%
%
%
%Default values
%--------------
%Initialization was crude in first version, Nov 2016 tried to improve the
%initialization to reasonable first guess values. This is very
%cross-section dependent so it is kind of crude.
maxd=max(max(abs(node(:,2:3)))); %this is the max x or z cross-section dimension
%
%Member length
input1=10*maxd; %member length
%Distortional gross section half wavelength
Lcrd=3*maxd;
%Unbraced lengths
KL1=input1;
KL2=input1*0.5;
KL3=input1;
%Hole definition
%hole# Sstart Send Lhole Sstart_Plate Send_Plate
input2=[1 maxd  4/3*maxd  maxd 6/9*maxd 15/9*maxd
        2 2/9*maxd 4/9*maxd maxd 1/9*maxd 6/9*maxd];
%Hole starting location(s) along the length
%y={'1 3 4'
%'2 6'};
y{1}=num2str([1 2*maxd 8*maxd]);
y{2}=num2str([2 5*maxd]);
input3=sprintf('%s\n',y{:});
% input3=['80 160'...
%     '30'];
%For cross-section plotting, set the default flags and view
%flags:[node# element# mat# stress# stresspic coord constraints springs origin] 1 means show
flags_hole=[0 0 0 0 0 0 0 0 0 0 0 1];
%
%---------------end default calculations
%
%
%
%%
%LEFT PANE HOLE DEFINITION INPUTS
%------------------------------------------------
%TITLE AND HOLE DEFINITION
box=uipanel(subfig,...
    'units','normalized',...
    'Position',[0.0 0.0 0.25 1.00]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',14,...
    'Position',[0.01 0.94 .23 0.03],...
    'String','Specify Hole(s) and Lengths');
%About Button
btn_abouthelp=uicontrol(fig,...
	'Style','push','units','normalized',...
	'Position',[0.0 0.98 0.03 0.02],...
	'String','About',...
   'Callback',[...
      'cufsmhelp(400);']);
%HOLE LOCATION HEADER
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','left','fontweight','bold',...
    'Position',[0.01 0.91 .23 0.03],...
    'String','Define Hole Locations in Cross-Section');
%HOLE LOCATION IN THE SECTION
input2title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.01 0.88 0.23 0.03],...        
    'String','hole# Sstart Send Lhole Sstart_Plate Send_Plate');
input2edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
     'HorizontalAlignment','Left',...
    'Position',[0.01 0.8 0.23 0.08],...
    'CallBack','holehelper_cb(10);',...
    'String',num2str(input2),...
     'Max',100);
btn_prophelp=uicontrol(fig,...
	'Style','push','units','normalized',...
	'Position',[0.22 0.88 0.02 0.03],...
	'String','?',...
   'Callback',[...
      'holehelper_cb(3);']);
%HOLE LOCATION ALONG THE LENGTH
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','left','fontweight','bold',...
    'Position',[0.01 0.76 .23 0.03],...
    'String','Define Hole Start Location(s) Along the Length');
input3title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.01 0.73 0.23 0.03],...
    'String',['hole# hole_y_coordinate(s)']);
input3edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
      'HorizontalAlignment','Left',...
    'Position',[0.01 0.65 0.23 0.08],...
    'CallBack','holehelper_cb(10);',...
    'String',input3,...
         'Max',100);
%DISTORTIONAL BUCKLING INPUTS
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','left','fontweight','bold',...
    'Position',[0.01 0.61 .23 0.03],...
    'String','Gross Section Distortional Buckling Input');
%Lcrd
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.58 .11 0.03],...
    'String','Distortional, Lcrd =');
input_Lcrd_edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.12 0.58 0.06 0.03],...
      'HorizontalAlignment','Left',...
    'CallBack','holehelper_cb(10);',...
    'String',num2str(Lcrd));
%GLOBAL BUCKLING INPUTS
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','left','fontweight','bold',...
    'Position',[0.01 0.54 .23 0.03],...
    'String','Global buckling unbraced length inputs');
input1title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.51 .11 0.03],...
    'String','Member Length, L =');
input1edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.12 0.51 0.06 0.03],...
      'HorizontalAlignment','Left',...
    'CallBack','holehelper_cb(10);',...
    'String',num2str(input1));
KLtitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.01 0.48 0.11 0.03],...
    'String','Unbraced length about the:');
KL1title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.45 0.11 0.03],...
    'String','1-axis, K1L =');
KL1edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.12 0.45 0.06 0.03],...
      'HorizontalAlignment','Left',...
    'String',num2str(KL1));    
KL2title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.42 0.11 0.03],...
    'String','2-axis, K2L =');
KL2edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.12 0.42 0.06 0.03],...
      'HorizontalAlignment','Left',...
    'String',num2str(KL2));
KL3title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.39 0.11 0.03],...
    'String','3-axis, K3L =');
KL3edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.12 0.39 0.06 0.03],...
      'HorizontalAlignment','Left',...
    'String',num2str(KL3));

%%APPLIED REFERENCE LOADS DETERMINED FROM APPLIED STRESSES
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','left','fontweight','bold',...
    'Position',[0.01 0.35 .23 0.03],...
    'String','Gross Section applied loads based on model');
Ptitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.32 0.05 0.03],...
    'String','P = ');
Pedit_hole=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.06 0.32 0.06 0.03]);
%B, bimoment
Btitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.126 0.32 0.05 0.03],...
    'String','B = ');
Bedit_hole=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.185 0.32 0.06 0.03]);
M11title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.29 0.05 0.03],...
    'String','M11 = ');
M11edit_hole=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.06 0.29 0.06 0.03]);
M22title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.126 0.29 0.05 0.03],...
    'String','M22 = ');
M22edit_hole=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.185 0.29 0.06 0.03]); 
     
%REFERENCE S COORDINATES FOR PLACING HOLES
Stitle0=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left','fontweight','bold',...
    'Position',[0.01 0.25 0.20 0.03],...        
    'String','Reference S Coordinates for locating holes');
Stitle=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.01 0.22 0.23 0.03],...        
    'String','Node# Scoordinate');
S2edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
     'HorizontalAlignment','Left',...
    'Position',[0.01 0.01 0.23 0.24],...
     'Max',100,'Enable','off');

%%
%PANE 2 CROSS-SECTION VIEWER AND SELECTION
%TITLE AND HOLE DEFINITION
%box=uipanel(subfig,...
%    'units','normalized',...
%    'Position',[0.25 0.00 0.25 1.0]);
%GENERATE NET SECTIONS
buildsurface=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.26 0.95 0.23 0.04],...
   'String','Generate Net Sections Based on Hole Inputs',...
   'CallBack',[...
   'holehelper_cb(10);']);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',14,...
    'Position',[0.26 0.92 .23 0.03],...
    'String','Net Section Viewer and Selection');
%CURRENT SECTION
label_cs_test=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'FontName','Arial','FontSize',16,...
    'FontWeight','bold',...
    'Position',[0.26+0.05 0.89 .12 0.03],...
    'String','Cross-Section No. = ');
label_cs=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'FontName','Arial','FontSize',16,...
    'FontWeight','bold',...
    'Position',[0.38+0.05 0.89 .05 0.03],...
    'String','1');
%SMALL PLOT OF SECTION LOCATION ALONG THE LENGTH
long_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.27 0.85 0.23 0.04],...
    'String','Location along the member');
axeslong=axes('Units','normalized','Position',[0.27 0.80 0.22 0.05],'visible','off');
% slider bar
range_slider = uicontrol('Style','slider','Units','normalized','Position',[0.27 0.70 0.22 0.04],...
    'Callback',[...
    'holehelper_cb(106);']);
% bgcolor = f.Color;
bl1 = uicontrol('Style','text','Units','normalized','Position',[0.27 0.74 0.05 0.03],...
                'String','0');
bl2 = uicontrol('Style','text','Units','normalized','Position',[0.44 0.74 0.05 0.03],...
                'String',' ');
bl3 = uicontrol('Style','text','Units','normalized','Position',[0.36 0.74 0.05 0.03],...
                'String','');
%Before and next section
leftbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.28 0.67 0.08 0.03],...
   'String','<Previous Section',...
   'CallBack',[...
   'holehelper_cb(5);']);
rightbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.40 0.67 0.08 0.03],...
   'String','Next Section>',...
   'CallBack',[...
   'holehelper_cb(6);']);
%CROSS-SECTION PLOT WITH PLOTTING OPTIONS
axessect=axes('Units','normalized','Position',[0.27 0.02 0.22 0.59],'visible','off');
% plot options
% Update, Plotting and Plot Options
popanel_hole=uipanel(subfig,...
   'units','normalized',...
   'visible','off',...
   'Position',[0.25 0.62-0.275 0.1 0.665-0.390]);

% 'Position',[0.4 0.390 0.1 0.665-0.390]);
% plotoptions=uicontrol(subfig,...
% 	'Style','push','units','normalized',...
% 	'HorizontalAlignment','Center',...
%    'Position',[0.41 0.665 0.08 0.03],..

plotoptions=uicontrol(subfig,...
	'Style','push','units','normalized',...
	'HorizontalAlignment','Center',...
    'visible','on',...
   'Position',[0.27 0.62 0.08 0.03],...
   'String','Plot Options:',...
   'Callback',[...
 		'holehelper_cb(220);']);
%     [0.01 0.05 0.49 0.659-0.05],'visible','off'
%All the various plotting options
%flags:[node# element# mat# stress# stresspic coord constraints springs origin propaxis] 1 means show
togglenode=uicontrol('Parent',popanel_hole,...
  'Style','checkbox','units','normalized',...
  'Position',[0.01 0.92 0.8 0.07],...
  'String','node #',...
  'Value',flags_hole(1),...
  'Callback',[...
		'holehelper_cb(204);']);
  %'Position',[0.01 0.635 0.08 0.03],...
toggleelem=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.83 0.8 0.07],...
   'String','element #',...
   'Value',flags_hole(2),...
   'Callback',[...
 		'holehelper_cb(205);']);
togglemat=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.74 0.8 0.07],...
   'String','material #',...
   'Value',flags_hole(3),...
   'Callback',[...
 		'holehelper_cb(206);']);
togglestress=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.65 0.8 0.07],...
   'String','stress mag.',...
   'Value',flags_hole(4),...
   'Callback',[...
 		'holehelper_cb(207);']);
togglestresspic=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.56 0.8 0.07],...
   'String','stress dist.',...
   'Value',flags_hole(5),...
   'Callback',[...
 		'holehelper_cb(208);']);
togglecoord=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.47 0.8 0.07],...
   'String','coordinates',...
   'Value',flags_hole(6),...
   'Callback',[...
 		'holehelper_cb(209);']);
toggleconstraints=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.38 0.8 0.07],...
   'String','constraints',...
   'Value',flags_hole(7),...
   'Callback',[...
 		'holehelper_cb(210);']);
togglesprings=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.29 0.8 0.07],...
   'String','springs',...
   'Value',flags_hole(8),...
   'Callback',[...
 		'holehelper_cb(211);']);
toggleorigin=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.21 0.8 0.07],...
   'String','origin',...
   'Value',flags_hole(9),...
   'Callback',[...
 		'holehelper_cb(212);']);
togglepropaxis=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.12 0.8 0.07],...
   'String','centroidal axes',...
   'Value',flags_hole(10),...
   'Callback',[...
 		'holehelper_cb(213);']); 
    togglescoord=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.02 0.8 0.07],...
   'String','Scoordinate',...
   'Value',flags_hole(11),...
   'Callback',[...
 		'holehelper_cb(214);']); 



%%
%ANALYSIS BUTTONS %
%label=uicontrol(subfig,...
%    'Style','text','units','normalized',...
%    'HorizontalAlignment','Center',...
%    'FontName','Arial','FontSize',14,...
%    'Position',[0.51 0.96 .48 0.03],...
%    'String','Approximate Hole Effect Analysis Engine');
globalbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.51 0.95 0.1 0.04],...
   'String','Properties & Global',...
   'CallBack',[...
   'holehelper_cb(103);']);
distortionalbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.61 0.95 0.1 0.04],...
   'String','Distortional Analyses',...
   'CallBack',[...
   'holehelper_cb(102);']);
localbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.71 0.95 0.1 0.04],...
   'String','Local Analyses',...
   'CallBack',[...
   'holehelper_cb(101);']);
buildsurface1=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.81 0.95 0.1 0.04],...
   'String','Generate files only',...
   'CallBack',[...
   'holehelper_cb(11);']);
runbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.91 0.95 0.09 0.04],...
   'String','Re-Run Analysis',...
   'CallBack',[...
   'holehelper_cb(104);']);





%%



halfwave=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.51 0.90 0.15 0.03],...
   'String','Half-wavelengths (as appropriate)');
hint=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.70 0.90 0.25 0.03],...
   'String','');
waveedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
      'HorizontalAlignment','Left',...
    'Position',[0.51 0.870 0.45 0.03]);
label=[' load factor ='];
label_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'Position',[0.580 0.52 0.3 0.03],...
    'String',label);
set(halfwave,'visible','off')
set(hint,'visible','off')
set(waveedit,'visible','off')
set(label_title,'visible','off')

 
% Get the Java scroll-pane container reference
jScrollPane = findjobj(S2edit);
 
set(jScrollPane,'VerticalScrollBarPolicy',20); 
% cbStr = sprintf('set(gcbo,''VerticalScrollBarPolicy'',%d)', ...
%                 jScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
% hjScrollPane = handle(jScrollPane,'CallbackProperties');
% set(hjScrollPane,'ComponentResizedCallback',cbStr);

% boxR=uicontrol(subfig,...
%     'Style','uipanel','units','normalized',...
%     'Position',[0.5 0.0 0.5 1.0]);

% box=uicontrol(subfig,...
%     'Style','frame','units','normalized',...
%     'Position',[0.0 0.0 0.25 1.00]);

%------------------------------------------------
%
%
%CROSS-SECTION PLOT
%------------------------------------------------
%box=uicontrol(subfig,...
%    'Style','frame','units','normalized',...
%    'Position',[0.0 0.0 0.50 0.70]);
axescurve_hole=axes('Units','normalized','Position',[0.55 0.12 0.43 0.40],'Box','on','XTickLabel','','YTickLabel','','visible','off');
axes2dshape_hole=axes('Units','normalized','Position',[0.580 0.56 0.3 0.30],'visible','off');

len_cur_local=uicontrol(fig,...
    'Style','edit','units','normalized',...
    'Position',[0.76 0.02 0.04 0.03],...
    'FontName','Arial','FontSize',10,...
    'HorizontalAlignment','Center',...
    'String',' ');
uplengthl=uicontrol(fig,...
    'Style','push','units','normalized',...
    'Position',[0.80 0.02 0.04 0.03],...
    'fontname','symbol',...
    'String',setstr(hex2dec('ae')),...
    'Callback',[...
    'holehelper_cb(302);']);
downlengthl=uicontrol(fig,...
    'Style','push','units','normalized',...
    'Position',[0.71 0.02 0.04 0.03],...
    'fontname','symbol',...
    'String',setstr(hex2dec('ac')),...
    'Callback',[...
    'holehelper_cb(301);']);
set(len_cur_local,'visible','off')
set(uplengthl,'visible','off')
set(downlengthl,'visible','off')


cnames = {'load ratio'};


% Create the uitable
% table_hole = uicontrol(fig,...
%     'Style','edit','units','normalized',...
%     'Position',[0.91 0.62 0.08 0.25],...
%     'FontName','Arial','FontSize',10,...
%     'Max',100,...
%     'HorizontalAlignment','Center',...
%     'String',' ');
        
% record_hole = uicontrol(fig,...
%     'Style','push','units','normalized',...
%     'Position',[0.93 0.58 0.04 0.03],...
%     'String','record',...
%     'Callback',[...
%     'holehelper_cb(401);']);
% axes2dshape=axes('Units','normalized','Position',[0.510 0.63 0.3 0.32],'visible','off');
% axes equal off
% 
% addlistener(b,'ActionEvent',@(bObject, event) makeplot(bObject, event));




%plot current applied stress
% inode=node;
% % inode(:,8)=0*node(:,8);
% strespic(inode,elem,axesstres,scale)
% crossect(inode,elem,axessect,springs,constraints,flags)

      upperbox=uipanel(subfig,...
       'units','normalized',...
       'Visible',' Off',...
        'Position',[0.50 0.00 0.50 0.90]);    
    out2A=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.08 0.90 0.12 0.05],...
        'String',' ');
    out2xcg=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.07 0.85 0.12 0.05],...
        'String',' ');
    out2zcg=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.3 0.85 0.12 0.05],...
        'String',' ');
    out2Ixx=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.07 0.80 0.12 0.05],...
        'String',' ');
    out2Izz=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.3 0.80 0.12 0.05],...
        'String',' ');
    out2Ixz=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.07 0.75 0.12 0.05],...
        'String',' ');
    out2thetap=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.3 0.75 0.12 0.05],...
        'String',' ');
    out2I11=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.07 0.70 0.12 0.05],...
        'String',' ');
    out2I22=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.3 0.70 0.12 0.05],...
        'String',' ');  
    out2J=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.08 0.65 0.12 0.05],...
        'String',' ');
    out2C_w=uicontrol(upperbox,...
        'Style','text','units','normalized',...
        'HorizontalAlignment','Left',...
        'Position',[0.3 0.65 0.12 0.05],...
        'String','');
    %
%------------------------------------------------

%--------------------------------------------
%RHS EFFORTS
%------------------------------------------------
% box=uicontrol(subfig,...
%     'Style','frame','units','normalized',...
%     'Position',[0.5 0.0 0.5 1.0]);
% label=uicontrol(subfig,...
%     'Style','text','units','normalized',...
%     'HorizontalAlignment','Center',...
%     'FontName','Arial','FontSize',12,...
%     'Position',[0.51 0.96 .48 0.03],...
%     'String','RHS Stuff');

%DEFINE THE AXIS THAT WILL BE USED FOR THE TWO PLOTS
% axes2dshapelarge=axes('Units','normalized','Position',[0.51 0.43 0.6 0.32],'visible','on');
% axescurve_hole=axes('Units','normalized','Position',[0.51 0.07 0.43 0.43],'Box','on','XTickLabel','','YTickLabel','');
% axescurve_hole=axes('Units','normalized','Position',[0.51 0.07 0.43 0.43],'visible','off');
%for load factor vs mode number and participation of lonitudinal terms
% axesparticipation=axes('Units','normalized','Position',[0.51 0.37 0.42 0.14],'Box','on','XTickLabel','','YTickLabel','','visible','off');
% axescurvemode=axes('Units','normalized','Position',[0.51 0.07 0.42 0.23],'Box','on','XTickLabel','','YTickLabel','','visible','off');
%  ilocation=str2num(get(ed_location,'String'));
    var_length= str2num(get(input1edit,'string'));
    temp_location=str2num(get(input2edit,'string'));
ed_location=temp_location(:,1:4);
 
%     len=length(ed_location);
%     for i=1:len
%     ed_location{i}(:,1)=[];
%     end
%      ed_location_x=str2num(get(input3edit,'string'));
% ed_location=(get(input2edit,'string'));
      ed_location_x=get(input3edit,'string');
          assignin('base', 'ed_location_x', ed_location_x);
       
              ed_location_x(:,1)=[];
 

   
% axessect=axes('Units','normalized','Position',[0.27 0.2 0.22 0.78],'visible','off');
%plot current applied stress

      
%      [  node_all4plot,cross_section_range,node_all,elem_all,binary_exist ] =hole_fun_general( var_length,ed_location, ed_location_x,elem,node );

 [A,xcg,zcg,Ixx,Izz,Ixz,thetap,I11,I22,J,Xs,Ys,Cw,B1,B2,w] = cutwp_prop2(node(:,2:3),elem(:,2:4));
  [P,M11,M22,B,err] = stress_to_action(node,xcg,zcg,thetap,A,I11,I22,w,Cw);
  maxP=max([P M11 M22 B]);
        if abs(P/maxP)<0.001, P=0;, end
        if abs(B/maxP)<0.001, B=0;, end
        if abs(M11/maxP)<0.001, M11=0;, end
        if abs(M22/maxP)<0.001, M22=0;, end  
  
%       [ node4local,elem4local ] =hole_fun_local( node_all,elem_all,P,0,0,M11,M22);
    
set(label_cs,'string',1); 
cla(axessect)
scale=1;
flags_hole=zeros(11,1);
flags_hole(11)=1;

crossect_hole(node,elem,axessect,springs,constraints,flags_hole)

set(togglescoord,'Value',1)

set(Pedit_hole,'String',num2str(P));  
set(Bedit_hole,'String',num2str(B));  
set(M11edit_hole,'String',num2str(M11));  
set(M22edit_hole,'String',num2str(M22));  

node4local{1}=node;
[maxNode,~]=size(node4local{1});
%calculate distance along the cross section to each node("s" coordinate)
node_location= node4local{1}(:,1:3);
node_location(1,4)=0;
[maxNode,~]=size(node4local{1});
s_coordinate(1)=0;
for i=2:maxNode
    dx{i}=node_location(i,2)- node_location((i-1),2);
    dz{i}=node_location(i,3)- node_location((i-1),3);
    ds(i)=sqrt(dx{i}^2 + dz{i}^2);
    
    s_coordinate(i,1)=s_coordinate(i-1)+ds(i);
end 
s_display(:,1)=1:maxNode;
s_display(:,2)=s_coordinate;
set(S2edit,'String',num2str(s_display));

%%
      lowerbox=uipanel(subfig,...
       'units','normalized',...
       'Visible',' Off',...
        'Position',[0.51 0.01 0.48 0.5]);
%Fire up CUTWP
% if screen==0
%     pre2;
% end
% %if lengths empty (since it is done in a separate step)
% if isempty(lengths)
%     lengths(1)=1;
% end
% %save key variable to temp file in cutwp directory
% if ispc %pc
%     save([currentlocation,'\cutwp\fromcufsm'],'prop','node','elem','lengths');
% else %mac! or unix
%     save([currentlocation,'/cutwp/fromcufsm'],'prop','node','elem','lengths');
% end
% cutwp;
% cutwp('FromCUFSM');


%%
%Splash the About for this tool on to the screen so the user is aware this
%code is a bit odd and requires special consideration to use.
cufsmhelp(400)

end





function makeplot(bObject,event)
global bl3 cross_section_range label_cs node_all4plot axessect axeslong var_length
n = get(bObject,'Value');
set(bl3,'String',num2str(n))
totalCS=length(cross_section_range);
for i=1:totalCS
    for j=length(cross_section_range{i})/2
    if n>=cross_section_range{i}(2*j-1) && n<=cross_section_range{i}(2*j)
              CSNO=i;  
        break  
    end
    end
end
set(label_cs,'string',num2str(CSNO)); 
     Net_cross_section_plotter4500( axessect,axeslong,cross_section_range{CSNO},var_length,node_all4plot{CSNO});

end

function axes_click
global axescurve_hole curvel modedisplayl len_cur_local idx_hole_l
global curvecelll filenamecelll clascelll filedisplayl minoptl logoptl clasoptl axescurvel xminl xmaxl yminl ymaxl modedisplayl fileindexl modeindexl picpointl
 pickpoint=get(axescurve_hole,'CurrentPoint'); 
     
     for j=1:max(size(curvel));
    curve_sign(j,1)=curvel{j}(modedisplayl(1),1);
    curve_sign(j,2)=curvel{j}(modedisplayl(1),2);
    if length(modedisplayl)>1
        for mn=2:length(modedisplayl)
            templ(j,modedisplayl(mn))=curvel{j}(modedisplayl(mn),1);
            templf(j,modedisplayl(mn))=curvel{j}(modedisplayl(mn),2);
        end
    end
end
if length(modedisplayl)>1
    [reldiff(1),pickminindex(1)]=min(sqrt((curve_sign(:,1)-pickpoint(1,1)).^2+(curve_sign(:,2)-pickpoint(1,2)).^2));
    for i=2:length(modedisplayl)
        [reldiff(i),pickminindex(i)]=min(sqrt((templ(:,i)-pickpoint(1,1)).^2+(templf(:,i)-pickpoint(1,2)).^2));
    end
    [minreldiff,mindiffindex]=min(reldiff);
    modeindexl=mindiffindex;
    idx_hole_l=pickminindex(modeindexl);
else
    [reldiff,pickminindex]=min(sqrt((curve_sign(:,1)-pickpoint(1,1)).^2+(curve_sign(:,2)-pickpoint(1,2)).^2));
    idx_hole_l=pickminindex;
    % modeindex=1;
end
set(len_cur_local,'String',num2str(lengths_local(idx_hole_l)));
picpointl=[curvel{idx_hole_l}(modeindexl,1) curvel{idx_hole_l}(modeindexl,2)];
    thecurve3(curvecelll,filenamecelll,clascelll,filedisplayl,minoptl,logoptl,clasoptl,axescurvel,xminl,xmaxl,yminl,ymaxl,modedisplayl,fileindexl,modeindexl,picpointl)
    111111111111111111111111
% set(len_cur,'String',['length = ',num2str(lengths(lengthindex))]);
% modes=(1:1:length(curvel{idx_hole_l}(:,2)));
% set(mode_cur,'String',num2str(modes(modeindexl)));
 
end
%
