%labeled version 4.0 on 3 May 2012
%abaqus_me
%GUI to generate abaqus files from CUFSM files
% Modified by Z. Li, March 1, 2011 to accommodate CUFSM4 
% Add functionality when using generalized FSM results. Perticularly if one
% wants to add the 1st mode as imperfection.

global pathname filename prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all elemtype elemtp nelbsp nelbct
global axessect flags filename_txt ed_filename ed_impmag ed_length ed_numele ed_elemtype txt_msg buckling static txt_nelbsp ed_nelbsp txt_nelbct ed_nelbct
%
%path statements to functions and interface usful for organization in matlab
w=what;
currentlocation=w.path;
addpath([currentlocation]);
if ispc %pc
    addpath([currentlocation,'\abaqusmaker\abaqus_me_subs']);
else %mac! or unix
    addpath([currentlocation,'/abaqusmaker/abaqus_me_subs']);
end

%
%Title
name=['CUFSM to ABAQUS -- Generating ABQUS input files from CUFSM'];
fig=figure('Name',name,...
   	'NumberTitle','off');
% set(fig,'Units','normalized')%
set(fig,'MenuBar','none');
set(fig,'position',[15 50 1000 750])%
% set(fig,'position',[0.10 0.25 0.45 .6])%
%
%default section that comes up from the beginning
load fromcufsm %default cross-section
if ispc
    pathname=[[currentlocation,'\abaqus_me_subs\']];
else
    pathname=[[currentlocation,'/abaqus_me_subs/']];
end
filename=['fromcufsm.mat'];
mag=zeros(length(lengths),1);
L=100;
nele=40;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
elemtp=1;%element types: 1-S9R5;2-S4;3-S4R
nelbsp=1; %Number of elements between springs, used to discretize springs
nelbct=1; %Number of elements between contraints, used to discretize const.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%Cross-section
axessect=axes('Units','normalized','Position',[0.51 0.1 0.48 0.52],'visible','off');
%flags:[node# element# mat# stress# stresspic coord constraints springs origin] 1 means show
flags=[0 0 0 0 0 0 1 1 1]; 
crossect(node,elem,axessect,springs,constraints,flags);
%
%Name
title_txt=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',16,...
   'Position',[0.1 0.93 0.8 0.05],...
   'String','CUFSM to ABAQUS');
%Input file
in_txt=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.1 0.89 0.05 0.03],...
   'String','in:');
filename_txt=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.15 0.89 0.75 0.03],...
   'String',num2str([pathname,filename]));
%Outputfile
out_txt=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.1 0.85 0.05 0.03],...
   'String','out:');
savefile=filename;
savefile(length(filename)-3:length(filename))=['.inp'];
ed_filename=uicontrol(fig,...
	'Style','edit','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.15 0.85 0.75 0.03],...
   'String',num2str([pathname,savefile]));
%
%Load
btn_load=uicontrol(fig,...
	'Style','push','units','normalized',...
	'Position',[0.1 0.8 0.3 0.04],...
	'String','Load CUFSM File',...
    'Tooltip','Load CUFSM file for generating ABAQUS input',...
    'Callback',[...
      'abaqus_me_cb(1);']);
%
%Save
btn_save=uicontrol(fig,...
	'Style','push','units','normalized',...
	'Position',[0.6 0.8 0.3 0.04],...
	'String','Generate ABAQUS .inp file',...
    'Tooltip','Generate ABAQUS.inp file',...
    'Callback',[...
      'abaqus_me_cb(2);']);
%
%Imperfection magnitudes
title_impmag=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
    'FontName','Arial','FontSize',12,...
   'Position',[0.1 0.7 0.4 0.03],...
   'String','Imperfection Seeds');
txt_impmag=uicontrol(fig,...
	'Style','text','units','normalized',...
	'Position',[0.1 0.65 0.4 0.03],...
	'HorizontalAlignment','Left',...
	'String','1/2 wavelength | load factor | imp. mag.');
if iscell(curve)
    nlength=max(size(curve));
    for i=1:nlength
        curve1(i,:)=curve{i}(1,:);
    end
    set(ed_impmag,'String',sprintf('%f %f %f\n',[curve1(:,1:2) mag]'));
else
    ed_impmag=uicontrol(fig,...
        'Style','edit','units','normalized',...
        'HorizontalAlignment','Left',...
        'String',num2str([curve(:,1:2) mag],'%5.5f %5.5f %5.5f'),...
        'Position',[0.1 0.1 0.4 0.55],...
        'Max',1000,...
        'Callback',[...
        'abaqus_me_cb(5);']);
end
%
%Buckling/Static toggle
buckling=uicontrol(fig,...
   'Style','radio','units','normalized',...
   'Position',[0.6 0.75 0.15 0.05],...
   'String','buckling',...
   'Value',1,...
   'CallBack',[...
		'abaqus_me_cb(3);']);
static=uicontrol(fig,...
   'Style','radio','units','normalized',...
   'Position',[0.75 0.75 0.15 0.05],...
   'String','static',...
   'Value',0,...
   'CallBack',[...
		'abaqus_me_cb(4);']);

%
%Length and Number of elements
txt_length=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.6 0.72 0.2 0.03],...
   'String','Member Length');
ed_length=uicontrol(fig,...
	'Style','edit','units','normalized',...
	'HorizontalAlignment','Left',...
 	'Position',[0.8 0.72 0.1 0.03],...
	'String',num2str(L),...
	'Max',1);
txt_numele=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.6 0.70 0.2 0.03],...
   'String','Number of elements');
ed_numele=uicontrol(fig,...
	'Style','edit','units','normalized',...
	'HorizontalAlignment','Left',...
 	'Position',[0.8 0.70 0.1 0.03],...
	'String',num2str(nele),...
	'Max',1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%added by Zhanjie for selection of element types and also defining springs
%and constraints along the longitudinal length. 
txt_elemtype=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.6 0.68 0.2 0.03],...
   'String','Elememt types (1-S9R5;2-S4;3-S4R)');
ed_elemtype=uicontrol(fig,...
	'Style','edit','units','normalized',...
	'HorizontalAlignment','Left',...
 	'Position',[0.8 0.68 0.1 0.03],...
	'String',num2str(elemtp),...
	'Max',1);
txt_nelbsp=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.6 0.66 0.2 0.03],...
   'String','Number of elements between springs');
ed_nelbsp=uicontrol(fig,...
	'Style','edit','units','normalized',...
	'HorizontalAlignment','Left',...
 	'Position',[0.8 0.66 0.1 0.03],...
	'String',num2str(nelbsp),...
	'Max',1);
txt_nelbct=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.6 0.64 0.2 0.03],...
   'String','Number of elements between contraints');
ed_nelbct=uicontrol(fig,...
	'Style','edit','units','normalized',...
	'HorizontalAlignment','Left',...
 	'Position',[0.8 0.64 0.1 0.03],...
	'String',num2str(nelbct),...
	'Max',1);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
txt_msg=uicontrol(fig,...
	'Style','text','units','normalized',...
	'HorizontalAlignment','Left',...
   'Position',[0.1 0.05 0.8 0.03],...
   'String','Ben Schafer (Luiz Vieira), December 2015, version0.2, www.ce.jhu.edu/bschafer ');






