function holehelper;
%BWS March 2016 - initial template
%Junle Cai - notes.. 
%
%general
global fig screen prop node elem lengths curve shapes clas springs constraints GBTcon BC m_all neigs version screen
%output from pre2
global subfig ed_prop ed_node ed_elem ed_lengths axestop screen flags modeflag ed_springs ed_constraints
%output from load file
global filename
%output from holehelper
global popanel flags axessect input1edit input2edit input3edit label_cs axeslong b bl1 bl2 bl3 P axescurve_hole axes2dshape_hole
global halfwave hint waveedit

global undefl nodel eleml model axes2dshapel scalel springsl m_al BCl SurfPosl shapesl len_cur_distorl idx_hole_l lengths_local  curve_local 
global curvecelll filenamecelll clascelll filedisplayl minoptl logoptl clasoptl axescurvel xminl xmaxl yminl ymaxl modedisplayl  fileindexl modeindexl picpointl
global screen Ix_avg Iy_avg I1_avg I2_avg len_cur_local modeindex lengthindex
global xmin xmax ymin ymax modeindex_local picpoint curvel shapescelll J_avg Cw_avg record_hole table_hole
global popanel_hole flags_hole flag_s

%This is code to run this tool as a subfigure
%comment out and uncomment section below depending on how interface desired
% subfig=figure;
% name=['CUFSM v',version,' -- Plastic Surface Builder'];
% set(subfig,'Name',name,'NumberTitle','off');
% set(subfig,'MenuBar','none');
% set(subfig,'position',[50 70 1024 633])%

%This is code to run this tool in the main screen
clf
pause(0.01)
name=['CUFSM v',version,' -- Hole Effect Analysis Tool'];
set(fig,'Name',name);
subfig=fig;
screen=9;
commandbar;
%
%------------------------------------------------------------------------------------
%
%
%
%Default values
%--------------
%Lots of boxes need initial values, put those initial values here
input1=300;
input2=[1 7 9 40;2  10  11 30 ];
y={'80 160'
'30'};
input3=sprintf('%s\n',y{:});
% input3=['80 160'...
%     '30'];
%For cross-section plotting, set the default flags and view
%flags:[node# element# mat# stress# stresspic coord constraints springs origin] 1 means show
flags_hole=[0 0 0 0 0 0 0 0 0 0 0 1];



%
%---------------end default calculations
%
%
%
%LEFT HALF HOLE DEFINITION INPUTS
%------------------------------------------------
box=uicontrol(subfig,...
    'Style','frame','units','normalized',...
    'Position',[0.0 0.0 0.25 1.00]);
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.01 0.96 .23 0.03],...
    'String','Hole Definitions');
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Left',...
    'Position',[0.01 0.93 .23 0.03],...
    'String','Member Length =');
%Hole Input 1
input1title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.88 0.05 0.03],...
    'String',' ');
input1edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
    'Position',[0.06 0.88 0.06 0.03],...
      'HorizontalAlignment','Left',...
    'String',num2str(input1),...
    'Callback',[...
    'holehelper_cb(1);']);
%Hole input 2 second leve label
label=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'Position',[0.01 0.84 .23 0.03],...
    'String','Hole Locations');
%Hole Input 2
input2title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.80 0.15 0.03],...        
    'String','hole# Sstart Send Lhole ');
input2edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
     'HorizontalAlignment','Left',...
    'Position',[0.06 0.5 0.18 0.28],...
    'String',num2str(input2),...
     'Max',100,...
    'Callback',[...
    'holehelper_cb(3);']);
%Left and right buttons for something
leftbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.30 0.02 0.08 0.03],...
   'String','<Before',...
   'CallBack',[...
   'holehelper_cb(5);']);
rightbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.40 0.02 0.08 0.03],...
   'String','Next>',...
   'CallBack',[...
   'holehelper_cb(6);']);
%More inputs
input3title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Right',...
    'Position',[0.01 0.40 0.20 0.04],...
    'String','y (hole coordinate along the member)');
input3edit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
      'HorizontalAlignment','Left',...
    'Position',[0.06 0.16 0.18 0.23],...
    'String',input3,...
         'Max',100,...
    'Callback',[...
    'holehelper_cb(4);']);
%Button for plotting or something
buildsurface=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.02 0.10 0.21 0.04],...
   'String','Calculate Net Cross-Section',...
   'CallBack',[...
   'holehelper_cb(10);']);

buildsurface1=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.02 0.02 0.21 0.04],...
   'String','Generate FSM input files',...
   'CallBack',[...
   'holehelper_cb(11);']);


localbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.51 0.95 0.1 0.03],...
   'String','Local',...
   'CallBack',[...
   'holehelper_cb(101);']);
distortionalbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.65 0.95 0.08 0.03],...
   'String','Distortional',...
   'CallBack',[...
   'holehelper_cb(102);']);
globalbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.75 0.95 0.08 0.03],...
   'String','Distortional',...
   'CallBack',[...
   'holehelper_cb(102);']);

runbutton=uicontrol(subfig,...
   'Style','push','units','normalized',...
   'Position',[0.96 0.92 0.03 0.03],...
   'String','Run',...
   'CallBack',[...
   'holehelper_cb(104);']);

halfwave=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.51 0.90 0.15 0.03],...
   'String','Half-wave lengths');
hint=uicontrol(subfig,...
   'Style','text','units','normalized',...
   'Position',[0.70 0.90 0.25 0.03],...
   'String','');

waveedit=uicontrol(subfig,...
    'Style','edit','units','normalized',...
      'HorizontalAlignment','Left',...
    'Position',[0.51 0.870 0.45 0.03]);

% boxR=uicontrol(subfig,...
%     'Style','uipanel','units','normalized',...
%     'Position',[0.5 0.0 0.5 1.0]);

% box=uicontrol(subfig,...
%     'Style','frame','units','normalized',...
%     'Position',[0.0 0.0 0.25 1.00]);

%------------------------------------------------
%
%
%CROSS-SECTION PLOT
%------------------------------------------------
%box=uicontrol(subfig,...
%    'Style','frame','units','normalized',...
%    'Position',[0.0 0.0 0.50 0.70]);
label_cs=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','Center',...
    'FontName','Arial','FontSize',12,...
    'Position',[0.27 0.96 .12 0.03],...
    'String','1');
%Define the axis for the cross-section stress plots
axessect=axes('Units','normalized','Position',[0.27 0.3 0.22 0.48],'visible','off');
axescurve_hole=axes('Units','normalized','Position',[0.55 0.12 0.43 0.40],'Box','on','XTickLabel','','YTickLabel','');
 axes2dshape_hole=axes('Units','normalized','Position',[0.580 0.53 0.3 0.32],'visible','off');

len_cur_local=uicontrol(fig,...
    'Style','edit','units','normalized',...
    'Position',[0.76 0.02 0.04 0.03],...
    'FontName','Arial','FontSize',10,...
    'HorizontalAlignment','Center',...
    'String',' ');
uplengthl=uicontrol(fig,...
    'Style','push','units','normalized',...
    'Position',[0.80 0.02 0.04 0.03],...
    'fontname','symbol',...
    'String',setstr(hex2dec('ae')),...
    'Callback',[...
    'holehelper_cb(302);']);
downlengthl=uicontrol(fig,...
    'Style','push','units','normalized',...
    'Position',[0.71 0.02 0.04 0.03],...
    'fontname','symbol',...
    'String',setstr(hex2dec('ac')),...
    'Callback',[...
    'holehelper_cb(301);']);

cnames = {'load ratio'};

% Ptitle=uicontrol(subfig,...
%     'Style','text','units','normalized',...
%     'HorizontalAlignment','Right',...
%     'Position',[0.01+0.25 0.88 0.05 0.03],...
%     'String','P = ');
% Pedit=uicontrol(subfig,...
%     'Style','edit','units','normalized',...
%     'Position',[0.06+0.25 0.88 0.06 0.03]);
% %B, bimoment
% Btitle=uicontrol(subfig,...
%     'Style','text','units','normalized',...
%     'HorizontalAlignment','Right',...
%     'Position',[0.126+0.25 0.88 0.05 0.03],...
%     'String','B = ');
% Bedit=uicontrol(subfig,...
%     'Style','edit','units','normalized',...
%     'Position',[0.185+0.25 0.88 0.06 0.03]);
% %Principal M11, M22
% % principal=uicontrol(subfig,...
% %    'Style','radio','units','normalized',...
% %    'Position',[0.01 0.84 0.123 0.03],...
% %    'String','principal or');
% M11title=uicontrol(subfig,...
%     'Style','text','units','normalized',...
%     'HorizontalAlignment','Right',...
%     'Position',[0.01+0.25 0.8 0.05 0.03],...
%     'String','M11 = ');
% M11edit=uicontrol(subfig,...
%     'Style','edit','units','normalized',...
%     'Position',[0.06+0.25 0.8 0.06 0.03]);
% M22title=uicontrol(subfig,...
%     'Style','text','units','normalized',...
%     'HorizontalAlignment','Right',...
%     'Position',[0.01+0.25 0.76 0.05 0.03],...
%     'String','M22 = ');
% M22edit=uicontrol(subfig,...
%     'Style','edit','units','normalized',...
%     'Position',[0.06+0.25 0.76 0.06 0.03]);

% Create the uitable
% table_hole = uicontrol(fig,...
%     'Style','edit','units','normalized',...
%     'Position',[0.91 0.62 0.08 0.25],...
%     'FontName','Arial','FontSize',10,...
%     'Max',100,...
%     'HorizontalAlignment','Center',...
%     'String',' ');
        
% record_hole = uicontrol(fig,...
%     'Style','push','units','normalized',...
%     'Position',[0.93 0.58 0.04 0.03],...
%     'String','record',...
%     'Callback',[...
%     'holehelper_cb(401);']);
% axes2dshape=axes('Units','normalized','Position',[0.510 0.63 0.3 0.32],'visible','off');
% axes equal off
long_title=uicontrol(subfig,...
    'Style','text','units','normalized',...
    'HorizontalAlignment','	Left',...
    'Position',[0.27 0.2 0.22 0.05],...
    'String','Location along the member');
axeslong=axes('Units','normalized','Position',[0.27 0.15 0.22 0.05],'visible','off');

%slider bar
% b = uicontrol('Style','slider','Units','normalized','Position',[0.27 0.02 0.22 0.05],...
%               'min',0, 'max',1);
% % bgcolor = f.Color;
% bl1 = uicontrol('Style','edit','Units','normalized','Position',[0.27 0.08 0.05 0.04],...
%                 'String','0');
% bl2 = uicontrol('Style','edit','Units','normalized','Position',[0.45 0.08 0.05 0.04],...
%                 'String',' ');
% bl3 = uicontrol('Style','text','Units','normalized','Position',[0.36 0.08 0.05 0.04],...
%                 'String','');
% 
% addlistener(b,'ActionEvent',@(bObject, event) makeplot(bObject, event));




%plot current applied stress
% inode=node;
% % inode(:,8)=0*node(:,8);
% strespic(inode,elem,axesstres,scale)
% crossect(inode,elem,axessect,springs,constraints,flags)

% plot options
% Update, Plotting and Plot Options
popanel_hole=uipanel(subfig,...
   'units','normalized',...
   'visible','off',...
   'Position',[0.26 0.8-0.275 0.1 0.665-0.390]);

% 'Position',[0.4 0.390 0.1 0.665-0.390]);
% plotoptions=uicontrol(subfig,...
% 	'Style','push','units','normalized',...
% 	'HorizontalAlignment','Center',...
%    'Position',[0.41 0.665 0.08 0.03],..

plotoptions=uicontrol(subfig,...
	'Style','push','units','normalized',...
	'HorizontalAlignment','Center',...
    'visible','on',...
   'Position',[0.27 0.8 0.08 0.05],...
   'String','Plot Options:',...
   'Callback',[...
 		'holehelper_cb(220);']);
%     [0.01 0.05 0.49 0.659-0.05],'visible','off'
%All the various plotting options
%flags:[node# element# mat# stress# stresspic coord constraints springs origin propaxis] 1 means show
togglenode=uicontrol('Parent',popanel_hole,...
  'Style','checkbox','units','normalized',...
  'Position',[0.01 0.92 0.8 0.07],...
  'String','node #',...
  'Value',flags_hole(1),...
  'Callback',[...
		'holehelper_cb(204);']);
  %'Position',[0.01 0.635 0.08 0.03],...
toggleelem=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.83 0.8 0.07],...
   'String','element #',...
   'Value',flags_hole(2),...
   'Callback',[...
 		'holehelper_cb(205);']);
togglemat=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.74 0.8 0.07],...
   'String','material #',...
   'Value',flags_hole(3),...
   'Callback',[...
 		'holehelper_cb(206);']);
togglestress=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.65 0.8 0.07],...
   'String','stress mag.',...
   'Value',flags_hole(4),...
   'Callback',[...
 		'holehelper_cb(207);']);
togglestresspic=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.56 0.8 0.07],...
   'String','stress dist.',...
   'Value',flags_hole(5),...
   'Callback',[...
 		'holehelper_cb(208);']);
togglecoord=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.47 0.8 0.07],...
   'String','coordinates',...
   'Value',flags_hole(6),...
   'Callback',[...
 		'holehelper_cb(209);']);
toggleconstraints=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.38 0.8 0.07],...
   'String','constraints',...
   'Value',flags_hole(7),...
   'Callback',[...
 		'holehelper_cb(210);']);
togglesprings=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.29 0.8 0.07],...
   'String','springs',...
   'Value',flags_hole(8),...
   'Callback',[...
 		'holehelper_cb(211);']);
toggleorigin=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.21 0.8 0.07],...
   'String','origin',...
   'Value',flags_hole(9),...
   'Callback',[...
 		'holehelper_cb(212);']);
togglepropaxis=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.12 0.8 0.07],...
   'String','centroidal axes',...
   'Value',flags_hole(10),...
   'Callback',[...
 		'holehelper_cb(213);']); 
    togglescoord=uicontrol('Parent',popanel_hole,...
   'Style','checkbox','units','normalized',...
   'Position',[0.01 0.02 0.8 0.07],...
   'String','Scoordinate',...
   'Value',flags_hole(11),...
   'Callback',[...
 		'holehelper_cb(214);']); 
%------------------------------------------------

%--------------------------------------------
%RHS EFFORTS
%------------------------------------------------
% box=uicontrol(subfig,...
%     'Style','frame','units','normalized',...
%     'Position',[0.5 0.0 0.5 1.0]);
% label=uicontrol(subfig,...
%     'Style','text','units','normalized',...
%     'HorizontalAlignment','Center',...
%     'FontName','Arial','FontSize',12,...
%     'Position',[0.51 0.96 .48 0.03],...
%     'String','RHS Stuff');

%DEFINE THE AXIS THAT WILL BE USED FOR THE TWO PLOTS
% axes2dshapelarge=axes('Units','normalized','Position',[0.51 0.43 0.6 0.32],'visible','on');
% axescurve_hole=axes('Units','normalized','Position',[0.51 0.07 0.43 0.43],'Box','on','XTickLabel','','YTickLabel','');
% axescurve_hole=axes('Units','normalized','Position',[0.51 0.07 0.43 0.43],'visible','off');
%for load factor vs mode number and participation of lonitudinal terms
% axesparticipation=axes('Units','normalized','Position',[0.51 0.37 0.42 0.14],'Box','on','XTickLabel','','YTickLabel','','visible','off');
% axescurvemode=axes('Units','normalized','Position',[0.51 0.07 0.42 0.23],'Box','on','XTickLabel','','YTickLabel','','visible','off');
%  ilocation=str2num(get(ed_location,'String'));
    var_length= str2num(get(input1edit,'string'));
    ed_location=str2num(get(input2edit,'string'));
%      ed_location_x=str2num(get(input3edit,'string'));
% ed_location=(get(input2edit,'string'));
      ed_location_x=get(input3edit,'string');
   
% axessect=axes('Units','normalized','Position',[0.27 0.2 0.22 0.78],'visible','off');
%plot current applied stress

      
     [  node_all4plot,cross_section_range,node_all,elem_all ] =hole_fun_general( var_length,ed_location, ed_location_x,elem,node );
%      Net_cross_section_plotter4500( axessect,axeslong,cross_section_range{2},var_length,node_all{2}); 
     P=1;
     
      [ node4local,elem4local ] =hole_fun_local( node_all,elem_all,P,0,0,0,0);
    
%       [~,~,s_coordinate ] = scoordinate2xy( ed_location,node4local{1} );
set(label_cs,'string',1); 
cla(axessect)
scale=1;
flags_hole=zeros(11,1);
flags_hole(11)=1;
crossect_hole(node4local{1},elem4local{1},axessect,springs,constraints,flags_hole)
% strespic(inode,elem4local{1},axessect,scale)
end



function makeplot(bObject,event)
global bl3 cross_section_range label_cs node_all4plot axessect axeslong var_length
n = get(bObject,'Value');
set(bl3,'String',num2str(n))
totalCS=length(cross_section_range);
for i=1:totalCS
    for j=length(cross_section_range{i})/2
    if n>=cross_section_range{i}(2*j-1) && n<=cross_section_range{i}(2*j)
              CSNO=i;  
        break  
    end
    end
end
set(label_cs,'string',num2str(CSNO)); 
     Net_cross_section_plotter4500( axessect,axeslong,cross_section_range{CSNO},var_length,node_all4plot{CSNO});

end
%
